### PR TITLE
Guard from invalid cocina data

### LINKED ISSUE #1427: [PURL/prod] NoMethodError: undefined method 'match' for nil
## Backtrace

    line 225 of [PROJECT_ROOT]/app/models/purl_version.rb: PurlVersion::Metadata#publication_date
    line 14 of [PROJECT_ROOT]/app/views/purl/show.html.erb: block in _app_views_purl_show_html_erb___3625256255605846431_10888
    line 2 of [PROJECT_ROOT]/app/views/purl/show.html.erb: _app_views_purl_show_html_erb___3625256255605846431_10888

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49629/faults/122947494)

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #1427

### CODE REVIEW

File: app/models/purl_version.rb [hunk 1]
```diff
@@ -247,18 +247,28 @@ def doi_id
...
     def publication_date
       @publication_date ||= begin
         admin_metadata = cocina['description']['adminMetadata']
 
         creation_event = admin_metadata && admin_metadata['event']&.find { |node| node['type'] == 'creation' }
 
-        if creation_event && (matcher = creation_event['date'].first['value'].match(/(\d{4})/))
-          matcher[1]
+        if creation_event
+          date_value = creation_event['date'].first['value']
```
Comment (dnoneill) [inline app/models/purl_version.rb:258]: Is this going to work? It looked to me the error was calling first on creation_event['date'].first

Comment (dnoneill) [reply app/models/purl_version.rb:258]: nevermind
