### PR TITLE
fix manifest for pdfs

### LINKED ISSUE #1226: [PURL/prod] NoMethodError: undefined method 'id' for nil
## Backtrace

    line 128 of [PROJECT_ROOT]/app/models/iiif3_presentation_manifest.rb: Iiif3PresentationManifest#canvas_for_resource
    line 96 of [PROJECT_ROOT]/app/models/iiif3_presentation_manifest.rb: block in Iiif3PresentationManifest#build_canvases
    line 95 of [PROJECT_ROOT]/app/models/iiif3_presentation_manifest.rb: Array#each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49629/faults/117940744)

### PR DESCRIPTION
**Pull request by dnoneill**
closes #1226

### CODE REVIEW

File: app/models/iiif3_presentation_manifest.rb [hunk 1]
```diff
@@ -182,8 +182,9 @@ def supplementing_resources_annotation_page(resource_group)
   end
 
   def renderings_for_resource_group(resource_group)
+    ### renderings should not have probe services
```
Comment (jcoyne) [inline app/models/iiif3_presentation_manifest.rb:185]: Can you say why they should not? Is it a spec violation, or just because we don't need this info?

Comment (dnoneill) [reply app/models/iiif3_presentation_manifest.rb:185]: I think it is a spec violation. https://iiif.io/api/presentation/3.0/#rendering doesn't say anything about being able to have a service and it kind of doesn't make sense with what it is.

Comment (dnoneill) [reply app/models/iiif3_presentation_manifest.rb:185]: Thanks I missed that. I will go ahead and remove this change.
