### PR TITLE
fix thumbnail check, update height / width to be accurate

### LINKED ISSUE #1508: Citation only items in Mirador show "1 of 0" and don't show an image thumbnail
Citation-only items in Mirador are not showing a thumbnail. Instead, the viewer is blank and the page number indicator says "1 of 0".

Examples:

https://purl.stanford.edu/fw748fx1968
https://purl.stanford.edu/xq083mf5798

Image

### PR DESCRIPTION
**Pull request by dnoneill**
closes #1508

### CODE REVIEW

File: app/models/structural_metadata/file.rb [hunk 1]
```diff
@@ -55,6 +83,10 @@ def access
       @access ||= FileAccess.new json['access']
     end
 
+    def full_access?
```
Comment (jcoyne) [inline app/models/structural_metadata/file.rb:86]: This method name doesn't mean anything to me.   How about, `viewable_by_any_auth?` instead?

File: app/models/structural_metadata/file.rb [hunk 2]
```diff
@@ -35,6 +35,34 @@ def width
...
+      thumbnail_height
+    end
+
+    def manifest_width
+      return width if full_access?
+
+      thumbnail_width
+    end
+
+    def thumbnail_height
```
Comment (jcoyne) [inline app/models/structural_metadata/file.rb:50]: Can you add documentation about what you are doing here?  It seems to be preserving the aspect ratio and ensuring the long edge is 400px?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/models/structural_metadata/file.rb (hunk 1 above)
Comment (dnoneill) [reply app/models/structural_metadata/file.rb:86]: Maybe viewable?

File: app/models/structural_metadata/file.rb [hunk 3]
```diff
@@ -35,6 +35,34 @@ def width
       json.dig('presentation', 'width')
     end
 
+    def manifest_height
```
[the remark this answers is not in the document]
Comment (dnoneill) [reply app/models/structural_metadata/file.rb:38]: I think it should go in the file just be renamed. I think we want to keep it this way. The viewable width/height for things like citation only are always going to be the thumbnail size not the actual width/height.

**Review by jcoyne — APPROVED** [review]
